# Generated by Django 3.2.4 on 2021-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('todo_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('todo_title', models.CharField(max_length=70)),
                ('user_id', models.CharField(max_length=70)),
                ('check_date', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('ongoing', models.BooleanField(default=True)),
            ],
        ),
    ]
