# Generated by Django 3.2.4 on 2021-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_tt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TT',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='todo',
            name='check_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_id',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_title',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='todo',
            name='user_id',
            field=models.CharField(default='', max_length=70),
        ),
    ]
