# Generated by Django 3.2.4 on 2021-07-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_auto_20210704_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='id',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_id',
            field=models.CharField(default='', max_length=70, primary_key=True, serialize=False),
        ),
    ]
