# Generated by Django 3.2.4 on 2021-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0005_auto_20210706_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status',
            new_name='ongoing',
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_id',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.CharField(max_length=70),
        ),
    ]
