# Generated by Django 3.2.4 on 2021-07-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0007_auto_20210706_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='delete',
        ),
        migrations.AddField(
            model_name='todo',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
